## 데이터베이스 설정
spring:
  datasource:
    dfiver-sclass-name: cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root
    password: cyd68400
    
mybatis:
  mapper-locations: classpath:/sqlmap/sql_*.xml